[tool]
name = "uv"
version = "0.1.0"

[tool.torch]
version = "1.10.0"

[project]
name = "ann"
version = "0.1.0"
dependencies = [
    "black>=26.3.1",
    "flake8>=7.3.0",
    "ipykernel>=7.2.0",
    "matplotlib>=3.10.8",
    "pandas>=3.0.2",
    "pytest>=9.0.2",
    "scikit-learn>=1.8.0",
    "torch>=2.10.0",
    "torchvision>=0.25.0",
]
